# API key for for Gemini GenAI, Groq dan OCRSpace
GOOGLE_API_KEY="AIzaSyA-d6QJzHg0Ow7CM3bHvMS-ix1DrZn5SUk"
GROQ_API_KEY="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"
OCRSPACE_API_KEY="helloworld"

# .streamlit/config.toml

[server]
enableCORS = false
enableXsrfProtection = true

[client]
caching = true

[runner]
magicEnabled = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"

[logger]
level = "INFO"

[global]
disableUpdateWelcomeMessage = true
