# Secrets for GCP credentials & API keys
[gcp_service_account]
type = "service_account"
project_id = "divine-vehicle-470222-i0"
private_key_id = "02aaebc8aa69e9cd3ca74d9c2e08e6bab2df80fd"
private_key = "-----BEGIN PRIVATE KEY-----\n02aaebc8aa69e9cd3ca74d9c2e08e6bab2df80fd\n-----END PRIVATE KEY-----\n"
client_email = "roles-visionai-user@divine-vehicle-470222-i0.iam.gserviceaccount.com"
client_id = "110301979535382843606"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/110301979535382843606?project=divine-vehicle-470222-i0.iam.gserviceaccount.com"

# (Opsional) API key for other use, or Gemini key if needed
GOOGLE_API_KEY = "AIzaSyA-d6QJzHg0Ow7CM3bHvMS-ix1DrZn5SUk"  # optional: for Gemini GenAI if you use API key method
